# Generated by Django 4.1.7 on 2023-03-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_service_remove_user_facebook_remove_user_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='wage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
