# Generated by Django 4.1.7 on 2023-03-31 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_service_category_image_alter_service_title_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='service',
        ),
        migrations.AddField(
            model_name='user',
            name='is_worker',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.service')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.worker')),
            ],
        ),
    ]
