# Generated by Django 4.1.7 on 2023-03-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_category_image_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='We offer the given service'),
        ),
    ]
